services:

  embedding-service:
    build:
      context: ./embedding-service
      args:
        HF_TOKEN: ${HF_TOKEN}
    container_name: embedding-service
    ports:
      - 5001:5000
    environment:
      - MODEL_NAME=all-MiniLM-L6-v2

  postgres:
    image: ankane/pgvector:latest
    ports:
      - 5432:5432
    volumes:
      - /Users/liyi/ejoy/school/TechMemo/sql/data:/var/lib/postgresql/data
      - /Users/liyi/ejoy/school/TechMemo/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=techmemo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      retries: 10
      start_period: 1s
      timeout: 5s

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - /Users/liyi/ejoy/school/TechMemo/sql/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      retries: 10
      start_period: 1s
      timeout: 5s
