// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"techmemo/backend/model"
)

func newAiProcessLog(db *gorm.DB, opts ...gen.DOOption) aiProcessLog {
	_aiProcessLog := aiProcessLog{}

	_aiProcessLog.aiProcessLogDo.UseDB(db, opts...)
	_aiProcessLog.aiProcessLogDo.UseModel(&model.AiProcessLog{})

	tableName := _aiProcessLog.aiProcessLogDo.TableName()
	_aiProcessLog.ALL = field.NewAsterisk(tableName)
	_aiProcessLog.ID = field.NewInt64(tableName, "id")
	_aiProcessLog.SourceNoteID = field.NewInt64(tableName, "source_note_id")
	_aiProcessLog.TaskID = field.NewString(tableName, "task_id")
	_aiProcessLog.TargetType = field.NewString(tableName, "target_type")
	_aiProcessLog.TargetID = field.NewInt64(tableName, "target_id")
	_aiProcessLog.ProcessType = field.NewString(tableName, "process_type")
	_aiProcessLog.ModelName = field.NewString(tableName, "model_name")
	_aiProcessLog.Status = field.NewString(tableName, "status")
	_aiProcessLog.CreatedAt = field.NewTime(tableName, "created_at")

	_aiProcessLog.fillFieldMap()

	return _aiProcessLog
}

type aiProcessLog struct {
	aiProcessLogDo aiProcessLogDo

	ALL          field.Asterisk
	ID           field.Int64
	SourceNoteID field.Int64
	TaskID       field.String
	TargetType   field.String
	TargetID     field.Int64
	ProcessType  field.String
	ModelName    field.String
	Status       field.String
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (a aiProcessLog) Table(newTableName string) *aiProcessLog {
	a.aiProcessLogDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aiProcessLog) As(alias string) *aiProcessLog {
	a.aiProcessLogDo.DO = *(a.aiProcessLogDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aiProcessLog) updateTableName(table string) *aiProcessLog {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.SourceNoteID = field.NewInt64(table, "source_note_id")
	a.TaskID = field.NewString(table, "task_id")
	a.TargetType = field.NewString(table, "target_type")
	a.TargetID = field.NewInt64(table, "target_id")
	a.ProcessType = field.NewString(table, "process_type")
	a.ModelName = field.NewString(table, "model_name")
	a.Status = field.NewString(table, "status")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *aiProcessLog) WithContext(ctx context.Context) IAiProcessLogDo {
	return a.aiProcessLogDo.WithContext(ctx)
}

func (a aiProcessLog) TableName() string { return a.aiProcessLogDo.TableName() }

func (a aiProcessLog) Alias() string { return a.aiProcessLogDo.Alias() }

func (a aiProcessLog) Columns(cols ...field.Expr) gen.Columns {
	return a.aiProcessLogDo.Columns(cols...)
}

func (a *aiProcessLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aiProcessLog) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["source_note_id"] = a.SourceNoteID
	a.fieldMap["task_id"] = a.TaskID
	a.fieldMap["target_type"] = a.TargetType
	a.fieldMap["target_id"] = a.TargetID
	a.fieldMap["process_type"] = a.ProcessType
	a.fieldMap["model_name"] = a.ModelName
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a aiProcessLog) clone(db *gorm.DB) aiProcessLog {
	a.aiProcessLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aiProcessLog) replaceDB(db *gorm.DB) aiProcessLog {
	a.aiProcessLogDo.ReplaceDB(db)
	return a
}

type aiProcessLogDo struct{ gen.DO }

type IAiProcessLogDo interface {
	gen.SubQuery
	Debug() IAiProcessLogDo
	WithContext(ctx context.Context) IAiProcessLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAiProcessLogDo
	WriteDB() IAiProcessLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAiProcessLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAiProcessLogDo
	Not(conds ...gen.Condition) IAiProcessLogDo
	Or(conds ...gen.Condition) IAiProcessLogDo
	Select(conds ...field.Expr) IAiProcessLogDo
	Where(conds ...gen.Condition) IAiProcessLogDo
	Order(conds ...field.Expr) IAiProcessLogDo
	Distinct(cols ...field.Expr) IAiProcessLogDo
	Omit(cols ...field.Expr) IAiProcessLogDo
	Join(table schema.Tabler, on ...field.Expr) IAiProcessLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAiProcessLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAiProcessLogDo
	Group(cols ...field.Expr) IAiProcessLogDo
	Having(conds ...gen.Condition) IAiProcessLogDo
	Limit(limit int) IAiProcessLogDo
	Offset(offset int) IAiProcessLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAiProcessLogDo
	Unscoped() IAiProcessLogDo
	Create(values ...*model.AiProcessLog) error
	CreateInBatches(values []*model.AiProcessLog, batchSize int) error
	Save(values ...*model.AiProcessLog) error
	First() (*model.AiProcessLog, error)
	Take() (*model.AiProcessLog, error)
	Last() (*model.AiProcessLog, error)
	Find() ([]*model.AiProcessLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AiProcessLog, err error)
	FindInBatches(result *[]*model.AiProcessLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AiProcessLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAiProcessLogDo
	Assign(attrs ...field.AssignExpr) IAiProcessLogDo
	Joins(fields ...field.RelationField) IAiProcessLogDo
	Preload(fields ...field.RelationField) IAiProcessLogDo
	FirstOrInit() (*model.AiProcessLog, error)
	FirstOrCreate() (*model.AiProcessLog, error)
	FindByPage(offset int, limit int) (result []*model.AiProcessLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAiProcessLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aiProcessLogDo) Debug() IAiProcessLogDo {
	return a.withDO(a.DO.Debug())
}

func (a aiProcessLogDo) WithContext(ctx context.Context) IAiProcessLogDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aiProcessLogDo) ReadDB() IAiProcessLogDo {
	return a.Clauses(dbresolver.Read)
}

func (a aiProcessLogDo) WriteDB() IAiProcessLogDo {
	return a.Clauses(dbresolver.Write)
}

func (a aiProcessLogDo) Session(config *gorm.Session) IAiProcessLogDo {
	return a.withDO(a.DO.Session(config))
}

func (a aiProcessLogDo) Clauses(conds ...clause.Expression) IAiProcessLogDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aiProcessLogDo) Returning(value interface{}, columns ...string) IAiProcessLogDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aiProcessLogDo) Not(conds ...gen.Condition) IAiProcessLogDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aiProcessLogDo) Or(conds ...gen.Condition) IAiProcessLogDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aiProcessLogDo) Select(conds ...field.Expr) IAiProcessLogDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aiProcessLogDo) Where(conds ...gen.Condition) IAiProcessLogDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aiProcessLogDo) Order(conds ...field.Expr) IAiProcessLogDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aiProcessLogDo) Distinct(cols ...field.Expr) IAiProcessLogDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aiProcessLogDo) Omit(cols ...field.Expr) IAiProcessLogDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aiProcessLogDo) Join(table schema.Tabler, on ...field.Expr) IAiProcessLogDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aiProcessLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAiProcessLogDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aiProcessLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IAiProcessLogDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aiProcessLogDo) Group(cols ...field.Expr) IAiProcessLogDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aiProcessLogDo) Having(conds ...gen.Condition) IAiProcessLogDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aiProcessLogDo) Limit(limit int) IAiProcessLogDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aiProcessLogDo) Offset(offset int) IAiProcessLogDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aiProcessLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAiProcessLogDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aiProcessLogDo) Unscoped() IAiProcessLogDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aiProcessLogDo) Create(values ...*model.AiProcessLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aiProcessLogDo) CreateInBatches(values []*model.AiProcessLog, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aiProcessLogDo) Save(values ...*model.AiProcessLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aiProcessLogDo) First() (*model.AiProcessLog, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiProcessLog), nil
	}
}

func (a aiProcessLogDo) Take() (*model.AiProcessLog, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiProcessLog), nil
	}
}

func (a aiProcessLogDo) Last() (*model.AiProcessLog, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiProcessLog), nil
	}
}

func (a aiProcessLogDo) Find() ([]*model.AiProcessLog, error) {
	result, err := a.DO.Find()
	return result.([]*model.AiProcessLog), err
}

func (a aiProcessLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AiProcessLog, err error) {
	buf := make([]*model.AiProcessLog, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aiProcessLogDo) FindInBatches(result *[]*model.AiProcessLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aiProcessLogDo) Attrs(attrs ...field.AssignExpr) IAiProcessLogDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aiProcessLogDo) Assign(attrs ...field.AssignExpr) IAiProcessLogDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aiProcessLogDo) Joins(fields ...field.RelationField) IAiProcessLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aiProcessLogDo) Preload(fields ...field.RelationField) IAiProcessLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aiProcessLogDo) FirstOrInit() (*model.AiProcessLog, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiProcessLog), nil
	}
}

func (a aiProcessLogDo) FirstOrCreate() (*model.AiProcessLog, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AiProcessLog), nil
	}
}

func (a aiProcessLogDo) FindByPage(offset int, limit int) (result []*model.AiProcessLog, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aiProcessLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aiProcessLogDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aiProcessLogDo) Delete(models ...*model.AiProcessLog) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aiProcessLogDo) withDO(do gen.Dao) *aiProcessLogDo {
	a.DO = *do.(*gen.DO)
	return a
}
