// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"techmemo/backend/model"
)

func newChatMessage(db *gorm.DB, opts ...gen.DOOption) chatMessage {
	_chatMessage := chatMessage{}

	_chatMessage.chatMessageDo.UseDB(db, opts...)
	_chatMessage.chatMessageDo.UseModel(&model.ChatMessage{})

	tableName := _chatMessage.chatMessageDo.TableName()
	_chatMessage.ALL = field.NewAsterisk(tableName)
	_chatMessage.ID = field.NewInt64(tableName, "id")
	_chatMessage.SessionID = field.NewInt64(tableName, "session_id")
	_chatMessage.UserID = field.NewInt64(tableName, "user_id")
	_chatMessage.Role = field.NewString(tableName, "role")
	_chatMessage.Content = field.NewString(tableName, "content")
	_chatMessage.TokenCount = field.NewInt32(tableName, "token_count")
	_chatMessage.CreatedAt = field.NewTime(tableName, "created_at")

	_chatMessage.fillFieldMap()

	return _chatMessage
}

type chatMessage struct {
	chatMessageDo chatMessageDo

	ALL        field.Asterisk
	ID         field.Int64
	SessionID  field.Int64
	UserID     field.Int64
	Role       field.String
	Content    field.String
	TokenCount field.Int32
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (c chatMessage) Table(newTableName string) *chatMessage {
	c.chatMessageDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chatMessage) As(alias string) *chatMessage {
	c.chatMessageDo.DO = *(c.chatMessageDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chatMessage) updateTableName(table string) *chatMessage {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.SessionID = field.NewInt64(table, "session_id")
	c.UserID = field.NewInt64(table, "user_id")
	c.Role = field.NewString(table, "role")
	c.Content = field.NewString(table, "content")
	c.TokenCount = field.NewInt32(table, "token_count")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *chatMessage) WithContext(ctx context.Context) IChatMessageDo {
	return c.chatMessageDo.WithContext(ctx)
}

func (c chatMessage) TableName() string { return c.chatMessageDo.TableName() }

func (c chatMessage) Alias() string { return c.chatMessageDo.Alias() }

func (c chatMessage) Columns(cols ...field.Expr) gen.Columns { return c.chatMessageDo.Columns(cols...) }

func (c *chatMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chatMessage) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["session_id"] = c.SessionID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["role"] = c.Role
	c.fieldMap["content"] = c.Content
	c.fieldMap["token_count"] = c.TokenCount
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c chatMessage) clone(db *gorm.DB) chatMessage {
	c.chatMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chatMessage) replaceDB(db *gorm.DB) chatMessage {
	c.chatMessageDo.ReplaceDB(db)
	return c
}

type chatMessageDo struct{ gen.DO }

type IChatMessageDo interface {
	gen.SubQuery
	Debug() IChatMessageDo
	WithContext(ctx context.Context) IChatMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChatMessageDo
	WriteDB() IChatMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChatMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChatMessageDo
	Not(conds ...gen.Condition) IChatMessageDo
	Or(conds ...gen.Condition) IChatMessageDo
	Select(conds ...field.Expr) IChatMessageDo
	Where(conds ...gen.Condition) IChatMessageDo
	Order(conds ...field.Expr) IChatMessageDo
	Distinct(cols ...field.Expr) IChatMessageDo
	Omit(cols ...field.Expr) IChatMessageDo
	Join(table schema.Tabler, on ...field.Expr) IChatMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChatMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChatMessageDo
	Group(cols ...field.Expr) IChatMessageDo
	Having(conds ...gen.Condition) IChatMessageDo
	Limit(limit int) IChatMessageDo
	Offset(offset int) IChatMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChatMessageDo
	Unscoped() IChatMessageDo
	Create(values ...*model.ChatMessage) error
	CreateInBatches(values []*model.ChatMessage, batchSize int) error
	Save(values ...*model.ChatMessage) error
	First() (*model.ChatMessage, error)
	Take() (*model.ChatMessage, error)
	Last() (*model.ChatMessage, error)
	Find() ([]*model.ChatMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChatMessage, err error)
	FindInBatches(result *[]*model.ChatMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChatMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChatMessageDo
	Assign(attrs ...field.AssignExpr) IChatMessageDo
	Joins(fields ...field.RelationField) IChatMessageDo
	Preload(fields ...field.RelationField) IChatMessageDo
	FirstOrInit() (*model.ChatMessage, error)
	FirstOrCreate() (*model.ChatMessage, error)
	FindByPage(offset int, limit int) (result []*model.ChatMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChatMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chatMessageDo) Debug() IChatMessageDo {
	return c.withDO(c.DO.Debug())
}

func (c chatMessageDo) WithContext(ctx context.Context) IChatMessageDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chatMessageDo) ReadDB() IChatMessageDo {
	return c.Clauses(dbresolver.Read)
}

func (c chatMessageDo) WriteDB() IChatMessageDo {
	return c.Clauses(dbresolver.Write)
}

func (c chatMessageDo) Session(config *gorm.Session) IChatMessageDo {
	return c.withDO(c.DO.Session(config))
}

func (c chatMessageDo) Clauses(conds ...clause.Expression) IChatMessageDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chatMessageDo) Returning(value interface{}, columns ...string) IChatMessageDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chatMessageDo) Not(conds ...gen.Condition) IChatMessageDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chatMessageDo) Or(conds ...gen.Condition) IChatMessageDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chatMessageDo) Select(conds ...field.Expr) IChatMessageDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chatMessageDo) Where(conds ...gen.Condition) IChatMessageDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chatMessageDo) Order(conds ...field.Expr) IChatMessageDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chatMessageDo) Distinct(cols ...field.Expr) IChatMessageDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chatMessageDo) Omit(cols ...field.Expr) IChatMessageDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chatMessageDo) Join(table schema.Tabler, on ...field.Expr) IChatMessageDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chatMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChatMessageDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chatMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IChatMessageDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chatMessageDo) Group(cols ...field.Expr) IChatMessageDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chatMessageDo) Having(conds ...gen.Condition) IChatMessageDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chatMessageDo) Limit(limit int) IChatMessageDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chatMessageDo) Offset(offset int) IChatMessageDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chatMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChatMessageDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chatMessageDo) Unscoped() IChatMessageDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chatMessageDo) Create(values ...*model.ChatMessage) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chatMessageDo) CreateInBatches(values []*model.ChatMessage, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chatMessageDo) Save(values ...*model.ChatMessage) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chatMessageDo) First() (*model.ChatMessage, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMessage), nil
	}
}

func (c chatMessageDo) Take() (*model.ChatMessage, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMessage), nil
	}
}

func (c chatMessageDo) Last() (*model.ChatMessage, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMessage), nil
	}
}

func (c chatMessageDo) Find() ([]*model.ChatMessage, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChatMessage), err
}

func (c chatMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChatMessage, err error) {
	buf := make([]*model.ChatMessage, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chatMessageDo) FindInBatches(result *[]*model.ChatMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chatMessageDo) Attrs(attrs ...field.AssignExpr) IChatMessageDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chatMessageDo) Assign(attrs ...field.AssignExpr) IChatMessageDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chatMessageDo) Joins(fields ...field.RelationField) IChatMessageDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chatMessageDo) Preload(fields ...field.RelationField) IChatMessageDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chatMessageDo) FirstOrInit() (*model.ChatMessage, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMessage), nil
	}
}

func (c chatMessageDo) FirstOrCreate() (*model.ChatMessage, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatMessage), nil
	}
}

func (c chatMessageDo) FindByPage(offset int, limit int) (result []*model.ChatMessage, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chatMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chatMessageDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chatMessageDo) Delete(models ...*model.ChatMessage) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chatMessageDo) withDO(do gen.Dao) *chatMessageDo {
	c.DO = *do.(*gen.DO)
	return c
}
