// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"techmemo/backend/model"
)

func newEmbedding(db *gorm.DB, opts ...gen.DOOption) embedding {
	_embedding := embedding{}

	_embedding.embeddingDo.UseDB(db, opts...)
	_embedding.embeddingDo.UseModel(&model.Embedding{})

	tableName := _embedding.embeddingDo.TableName()
	_embedding.ALL = field.NewAsterisk(tableName)
	_embedding.ID = field.NewInt64(tableName, "id")
	_embedding.TargetType = field.NewString(tableName, "target_type")
	_embedding.TargetID = field.NewInt64(tableName, "target_id")
	_embedding.Vector = field.NewString(tableName, "vector")
	_embedding.ModelName = field.NewString(tableName, "model_name")
	_embedding.CreatedAt = field.NewTime(tableName, "created_at")

	_embedding.fillFieldMap()

	return _embedding
}

type embedding struct {
	embeddingDo embeddingDo

	ALL        field.Asterisk
	ID         field.Int64
	TargetType field.String
	TargetID   field.Int64
	Vector     field.String
	ModelName  field.String
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (e embedding) Table(newTableName string) *embedding {
	e.embeddingDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e embedding) As(alias string) *embedding {
	e.embeddingDo.DO = *(e.embeddingDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *embedding) updateTableName(table string) *embedding {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.TargetType = field.NewString(table, "target_type")
	e.TargetID = field.NewInt64(table, "target_id")
	e.Vector = field.NewString(table, "vector")
	e.ModelName = field.NewString(table, "model_name")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *embedding) WithContext(ctx context.Context) IEmbeddingDo {
	return e.embeddingDo.WithContext(ctx)
}

func (e embedding) TableName() string { return e.embeddingDo.TableName() }

func (e embedding) Alias() string { return e.embeddingDo.Alias() }

func (e embedding) Columns(cols ...field.Expr) gen.Columns { return e.embeddingDo.Columns(cols...) }

func (e *embedding) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *embedding) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 6)
	e.fieldMap["id"] = e.ID
	e.fieldMap["target_type"] = e.TargetType
	e.fieldMap["target_id"] = e.TargetID
	e.fieldMap["vector"] = e.Vector
	e.fieldMap["model_name"] = e.ModelName
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e embedding) clone(db *gorm.DB) embedding {
	e.embeddingDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e embedding) replaceDB(db *gorm.DB) embedding {
	e.embeddingDo.ReplaceDB(db)
	return e
}

type embeddingDo struct{ gen.DO }

type IEmbeddingDo interface {
	gen.SubQuery
	Debug() IEmbeddingDo
	WithContext(ctx context.Context) IEmbeddingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEmbeddingDo
	WriteDB() IEmbeddingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEmbeddingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEmbeddingDo
	Not(conds ...gen.Condition) IEmbeddingDo
	Or(conds ...gen.Condition) IEmbeddingDo
	Select(conds ...field.Expr) IEmbeddingDo
	Where(conds ...gen.Condition) IEmbeddingDo
	Order(conds ...field.Expr) IEmbeddingDo
	Distinct(cols ...field.Expr) IEmbeddingDo
	Omit(cols ...field.Expr) IEmbeddingDo
	Join(table schema.Tabler, on ...field.Expr) IEmbeddingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEmbeddingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEmbeddingDo
	Group(cols ...field.Expr) IEmbeddingDo
	Having(conds ...gen.Condition) IEmbeddingDo
	Limit(limit int) IEmbeddingDo
	Offset(offset int) IEmbeddingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEmbeddingDo
	Unscoped() IEmbeddingDo
	Create(values ...*model.Embedding) error
	CreateInBatches(values []*model.Embedding, batchSize int) error
	Save(values ...*model.Embedding) error
	First() (*model.Embedding, error)
	Take() (*model.Embedding, error)
	Last() (*model.Embedding, error)
	Find() ([]*model.Embedding, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Embedding, err error)
	FindInBatches(result *[]*model.Embedding, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Embedding) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEmbeddingDo
	Assign(attrs ...field.AssignExpr) IEmbeddingDo
	Joins(fields ...field.RelationField) IEmbeddingDo
	Preload(fields ...field.RelationField) IEmbeddingDo
	FirstOrInit() (*model.Embedding, error)
	FirstOrCreate() (*model.Embedding, error)
	FindByPage(offset int, limit int) (result []*model.Embedding, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEmbeddingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e embeddingDo) Debug() IEmbeddingDo {
	return e.withDO(e.DO.Debug())
}

func (e embeddingDo) WithContext(ctx context.Context) IEmbeddingDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e embeddingDo) ReadDB() IEmbeddingDo {
	return e.Clauses(dbresolver.Read)
}

func (e embeddingDo) WriteDB() IEmbeddingDo {
	return e.Clauses(dbresolver.Write)
}

func (e embeddingDo) Session(config *gorm.Session) IEmbeddingDo {
	return e.withDO(e.DO.Session(config))
}

func (e embeddingDo) Clauses(conds ...clause.Expression) IEmbeddingDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e embeddingDo) Returning(value interface{}, columns ...string) IEmbeddingDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e embeddingDo) Not(conds ...gen.Condition) IEmbeddingDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e embeddingDo) Or(conds ...gen.Condition) IEmbeddingDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e embeddingDo) Select(conds ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e embeddingDo) Where(conds ...gen.Condition) IEmbeddingDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e embeddingDo) Order(conds ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e embeddingDo) Distinct(cols ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e embeddingDo) Omit(cols ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e embeddingDo) Join(table schema.Tabler, on ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e embeddingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e embeddingDo) RightJoin(table schema.Tabler, on ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e embeddingDo) Group(cols ...field.Expr) IEmbeddingDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e embeddingDo) Having(conds ...gen.Condition) IEmbeddingDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e embeddingDo) Limit(limit int) IEmbeddingDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e embeddingDo) Offset(offset int) IEmbeddingDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e embeddingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEmbeddingDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e embeddingDo) Unscoped() IEmbeddingDo {
	return e.withDO(e.DO.Unscoped())
}

func (e embeddingDo) Create(values ...*model.Embedding) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e embeddingDo) CreateInBatches(values []*model.Embedding, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e embeddingDo) Save(values ...*model.Embedding) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e embeddingDo) First() (*model.Embedding, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Embedding), nil
	}
}

func (e embeddingDo) Take() (*model.Embedding, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Embedding), nil
	}
}

func (e embeddingDo) Last() (*model.Embedding, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Embedding), nil
	}
}

func (e embeddingDo) Find() ([]*model.Embedding, error) {
	result, err := e.DO.Find()
	return result.([]*model.Embedding), err
}

func (e embeddingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Embedding, err error) {
	buf := make([]*model.Embedding, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e embeddingDo) FindInBatches(result *[]*model.Embedding, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e embeddingDo) Attrs(attrs ...field.AssignExpr) IEmbeddingDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e embeddingDo) Assign(attrs ...field.AssignExpr) IEmbeddingDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e embeddingDo) Joins(fields ...field.RelationField) IEmbeddingDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e embeddingDo) Preload(fields ...field.RelationField) IEmbeddingDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e embeddingDo) FirstOrInit() (*model.Embedding, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Embedding), nil
	}
}

func (e embeddingDo) FirstOrCreate() (*model.Embedding, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Embedding), nil
	}
}

func (e embeddingDo) FindByPage(offset int, limit int) (result []*model.Embedding, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e embeddingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e embeddingDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e embeddingDo) Delete(models ...*model.Embedding) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *embeddingDo) withDO(do gen.Dao) *embeddingDo {
	e.DO = *do.(*gen.DO)
	return e
}
