// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	AiProcessLog      *aiProcessLog
	Category          *category
	ChatMessage       *chatMessage
	ChatSession       *chatSession
	Embedding         *embedding
	KnowledgePoint    *knowledgePoint
	KnowledgeRelation *knowledgeRelation
	Note              *note
	NoteRootNode      *noteRootNode
	NoteTag           *noteTag
	NoteVersion       *noteVersion
	SearchHistory     *searchHistory
	Tag               *tag
	User              *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AiProcessLog = &Q.AiProcessLog
	Category = &Q.Category
	ChatMessage = &Q.ChatMessage
	ChatSession = &Q.ChatSession
	Embedding = &Q.Embedding
	KnowledgePoint = &Q.KnowledgePoint
	KnowledgeRelation = &Q.KnowledgeRelation
	Note = &Q.Note
	NoteRootNode = &Q.NoteRootNode
	NoteTag = &Q.NoteTag
	NoteVersion = &Q.NoteVersion
	SearchHistory = &Q.SearchHistory
	Tag = &Q.Tag
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		AiProcessLog:      newAiProcessLog(db, opts...),
		Category:          newCategory(db, opts...),
		ChatMessage:       newChatMessage(db, opts...),
		ChatSession:       newChatSession(db, opts...),
		Embedding:         newEmbedding(db, opts...),
		KnowledgePoint:    newKnowledgePoint(db, opts...),
		KnowledgeRelation: newKnowledgeRelation(db, opts...),
		Note:              newNote(db, opts...),
		NoteRootNode:      newNoteRootNode(db, opts...),
		NoteTag:           newNoteTag(db, opts...),
		NoteVersion:       newNoteVersion(db, opts...),
		SearchHistory:     newSearchHistory(db, opts...),
		Tag:               newTag(db, opts...),
		User:              newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AiProcessLog      aiProcessLog
	Category          category
	ChatMessage       chatMessage
	ChatSession       chatSession
	Embedding         embedding
	KnowledgePoint    knowledgePoint
	KnowledgeRelation knowledgeRelation
	Note              note
	NoteRootNode      noteRootNode
	NoteTag           noteTag
	NoteVersion       noteVersion
	SearchHistory     searchHistory
	Tag               tag
	User              user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		AiProcessLog:      q.AiProcessLog.clone(db),
		Category:          q.Category.clone(db),
		ChatMessage:       q.ChatMessage.clone(db),
		ChatSession:       q.ChatSession.clone(db),
		Embedding:         q.Embedding.clone(db),
		KnowledgePoint:    q.KnowledgePoint.clone(db),
		KnowledgeRelation: q.KnowledgeRelation.clone(db),
		Note:              q.Note.clone(db),
		NoteRootNode:      q.NoteRootNode.clone(db),
		NoteTag:           q.NoteTag.clone(db),
		NoteVersion:       q.NoteVersion.clone(db),
		SearchHistory:     q.SearchHistory.clone(db),
		Tag:               q.Tag.clone(db),
		User:              q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		AiProcessLog:      q.AiProcessLog.replaceDB(db),
		Category:          q.Category.replaceDB(db),
		ChatMessage:       q.ChatMessage.replaceDB(db),
		ChatSession:       q.ChatSession.replaceDB(db),
		Embedding:         q.Embedding.replaceDB(db),
		KnowledgePoint:    q.KnowledgePoint.replaceDB(db),
		KnowledgeRelation: q.KnowledgeRelation.replaceDB(db),
		Note:              q.Note.replaceDB(db),
		NoteRootNode:      q.NoteRootNode.replaceDB(db),
		NoteTag:           q.NoteTag.replaceDB(db),
		NoteVersion:       q.NoteVersion.replaceDB(db),
		SearchHistory:     q.SearchHistory.replaceDB(db),
		Tag:               q.Tag.replaceDB(db),
		User:              q.User.replaceDB(db),
	}
}

type queryCtx struct {
	AiProcessLog      IAiProcessLogDo
	Category          ICategoryDo
	ChatMessage       IChatMessageDo
	ChatSession       IChatSessionDo
	Embedding         IEmbeddingDo
	KnowledgePoint    IKnowledgePointDo
	KnowledgeRelation IKnowledgeRelationDo
	Note              INoteDo
	NoteRootNode      INoteRootNodeDo
	NoteTag           INoteTagDo
	NoteVersion       INoteVersionDo
	SearchHistory     ISearchHistoryDo
	Tag               ITagDo
	User              IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AiProcessLog:      q.AiProcessLog.WithContext(ctx),
		Category:          q.Category.WithContext(ctx),
		ChatMessage:       q.ChatMessage.WithContext(ctx),
		ChatSession:       q.ChatSession.WithContext(ctx),
		Embedding:         q.Embedding.WithContext(ctx),
		KnowledgePoint:    q.KnowledgePoint.WithContext(ctx),
		KnowledgeRelation: q.KnowledgeRelation.WithContext(ctx),
		Note:              q.Note.WithContext(ctx),
		NoteRootNode:      q.NoteRootNode.WithContext(ctx),
		NoteTag:           q.NoteTag.WithContext(ctx),
		NoteVersion:       q.NoteVersion.WithContext(ctx),
		SearchHistory:     q.SearchHistory.WithContext(ctx),
		Tag:               q.Tag.WithContext(ctx),
		User:              q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
