// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"techmemo/backend/model"
)

func newKnowledgePoint(db *gorm.DB, opts ...gen.DOOption) knowledgePoint {
	_knowledgePoint := knowledgePoint{}

	_knowledgePoint.knowledgePointDo.UseDB(db, opts...)
	_knowledgePoint.knowledgePointDo.UseModel(&model.KnowledgePoint{})

	tableName := _knowledgePoint.knowledgePointDo.TableName()
	_knowledgePoint.ALL = field.NewAsterisk(tableName)
	_knowledgePoint.ID = field.NewInt64(tableName, "id")
	_knowledgePoint.UserID = field.NewInt64(tableName, "user_id")
	_knowledgePoint.Name = field.NewString(tableName, "name")
	_knowledgePoint.Description = field.NewString(tableName, "description")
	_knowledgePoint.SourceNoteID = field.NewInt64(tableName, "source_note_id")
	_knowledgePoint.ImportanceScore = field.NewFloat64(tableName, "importance_score")
	_knowledgePoint.CreatedAt = field.NewTime(tableName, "created_at")

	_knowledgePoint.fillFieldMap()

	return _knowledgePoint
}

type knowledgePoint struct {
	knowledgePointDo knowledgePointDo

	ALL             field.Asterisk
	ID              field.Int64
	UserID          field.Int64
	Name            field.String
	Description     field.String
	SourceNoteID    field.Int64
	ImportanceScore field.Float64
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (k knowledgePoint) Table(newTableName string) *knowledgePoint {
	k.knowledgePointDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledgePoint) As(alias string) *knowledgePoint {
	k.knowledgePointDo.DO = *(k.knowledgePointDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledgePoint) updateTableName(table string) *knowledgePoint {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewInt64(table, "id")
	k.UserID = field.NewInt64(table, "user_id")
	k.Name = field.NewString(table, "name")
	k.Description = field.NewString(table, "description")
	k.SourceNoteID = field.NewInt64(table, "source_note_id")
	k.ImportanceScore = field.NewFloat64(table, "importance_score")
	k.CreatedAt = field.NewTime(table, "created_at")

	k.fillFieldMap()

	return k
}

func (k *knowledgePoint) WithContext(ctx context.Context) IKnowledgePointDo {
	return k.knowledgePointDo.WithContext(ctx)
}

func (k knowledgePoint) TableName() string { return k.knowledgePointDo.TableName() }

func (k knowledgePoint) Alias() string { return k.knowledgePointDo.Alias() }

func (k knowledgePoint) Columns(cols ...field.Expr) gen.Columns {
	return k.knowledgePointDo.Columns(cols...)
}

func (k *knowledgePoint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledgePoint) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 7)
	k.fieldMap["id"] = k.ID
	k.fieldMap["user_id"] = k.UserID
	k.fieldMap["name"] = k.Name
	k.fieldMap["description"] = k.Description
	k.fieldMap["source_note_id"] = k.SourceNoteID
	k.fieldMap["importance_score"] = k.ImportanceScore
	k.fieldMap["created_at"] = k.CreatedAt
}

func (k knowledgePoint) clone(db *gorm.DB) knowledgePoint {
	k.knowledgePointDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k knowledgePoint) replaceDB(db *gorm.DB) knowledgePoint {
	k.knowledgePointDo.ReplaceDB(db)
	return k
}

type knowledgePointDo struct{ gen.DO }

type IKnowledgePointDo interface {
	gen.SubQuery
	Debug() IKnowledgePointDo
	WithContext(ctx context.Context) IKnowledgePointDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKnowledgePointDo
	WriteDB() IKnowledgePointDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKnowledgePointDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKnowledgePointDo
	Not(conds ...gen.Condition) IKnowledgePointDo
	Or(conds ...gen.Condition) IKnowledgePointDo
	Select(conds ...field.Expr) IKnowledgePointDo
	Where(conds ...gen.Condition) IKnowledgePointDo
	Order(conds ...field.Expr) IKnowledgePointDo
	Distinct(cols ...field.Expr) IKnowledgePointDo
	Omit(cols ...field.Expr) IKnowledgePointDo
	Join(table schema.Tabler, on ...field.Expr) IKnowledgePointDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgePointDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgePointDo
	Group(cols ...field.Expr) IKnowledgePointDo
	Having(conds ...gen.Condition) IKnowledgePointDo
	Limit(limit int) IKnowledgePointDo
	Offset(offset int) IKnowledgePointDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgePointDo
	Unscoped() IKnowledgePointDo
	Create(values ...*model.KnowledgePoint) error
	CreateInBatches(values []*model.KnowledgePoint, batchSize int) error
	Save(values ...*model.KnowledgePoint) error
	First() (*model.KnowledgePoint, error)
	Take() (*model.KnowledgePoint, error)
	Last() (*model.KnowledgePoint, error)
	Find() ([]*model.KnowledgePoint, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KnowledgePoint, err error)
	FindInBatches(result *[]*model.KnowledgePoint, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.KnowledgePoint) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKnowledgePointDo
	Assign(attrs ...field.AssignExpr) IKnowledgePointDo
	Joins(fields ...field.RelationField) IKnowledgePointDo
	Preload(fields ...field.RelationField) IKnowledgePointDo
	FirstOrInit() (*model.KnowledgePoint, error)
	FirstOrCreate() (*model.KnowledgePoint, error)
	FindByPage(offset int, limit int) (result []*model.KnowledgePoint, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKnowledgePointDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k knowledgePointDo) Debug() IKnowledgePointDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgePointDo) WithContext(ctx context.Context) IKnowledgePointDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgePointDo) ReadDB() IKnowledgePointDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgePointDo) WriteDB() IKnowledgePointDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgePointDo) Session(config *gorm.Session) IKnowledgePointDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgePointDo) Clauses(conds ...clause.Expression) IKnowledgePointDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgePointDo) Returning(value interface{}, columns ...string) IKnowledgePointDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgePointDo) Not(conds ...gen.Condition) IKnowledgePointDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgePointDo) Or(conds ...gen.Condition) IKnowledgePointDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgePointDo) Select(conds ...field.Expr) IKnowledgePointDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgePointDo) Where(conds ...gen.Condition) IKnowledgePointDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgePointDo) Order(conds ...field.Expr) IKnowledgePointDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgePointDo) Distinct(cols ...field.Expr) IKnowledgePointDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgePointDo) Omit(cols ...field.Expr) IKnowledgePointDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgePointDo) Join(table schema.Tabler, on ...field.Expr) IKnowledgePointDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgePointDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgePointDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgePointDo) RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgePointDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgePointDo) Group(cols ...field.Expr) IKnowledgePointDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgePointDo) Having(conds ...gen.Condition) IKnowledgePointDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgePointDo) Limit(limit int) IKnowledgePointDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgePointDo) Offset(offset int) IKnowledgePointDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgePointDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgePointDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgePointDo) Unscoped() IKnowledgePointDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgePointDo) Create(values ...*model.KnowledgePoint) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgePointDo) CreateInBatches(values []*model.KnowledgePoint, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgePointDo) Save(values ...*model.KnowledgePoint) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgePointDo) First() (*model.KnowledgePoint, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgePoint), nil
	}
}

func (k knowledgePointDo) Take() (*model.KnowledgePoint, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgePoint), nil
	}
}

func (k knowledgePointDo) Last() (*model.KnowledgePoint, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgePoint), nil
	}
}

func (k knowledgePointDo) Find() ([]*model.KnowledgePoint, error) {
	result, err := k.DO.Find()
	return result.([]*model.KnowledgePoint), err
}

func (k knowledgePointDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KnowledgePoint, err error) {
	buf := make([]*model.KnowledgePoint, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgePointDo) FindInBatches(result *[]*model.KnowledgePoint, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgePointDo) Attrs(attrs ...field.AssignExpr) IKnowledgePointDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgePointDo) Assign(attrs ...field.AssignExpr) IKnowledgePointDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgePointDo) Joins(fields ...field.RelationField) IKnowledgePointDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgePointDo) Preload(fields ...field.RelationField) IKnowledgePointDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgePointDo) FirstOrInit() (*model.KnowledgePoint, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgePoint), nil
	}
}

func (k knowledgePointDo) FirstOrCreate() (*model.KnowledgePoint, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgePoint), nil
	}
}

func (k knowledgePointDo) FindByPage(offset int, limit int) (result []*model.KnowledgePoint, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgePointDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgePointDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgePointDo) Delete(models ...*model.KnowledgePoint) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgePointDo) withDO(do gen.Dao) *knowledgePointDo {
	k.DO = *do.(*gen.DO)
	return k
}
