// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"techmemo/backend/model"
)

func newKnowledgeRelation(db *gorm.DB, opts ...gen.DOOption) knowledgeRelation {
	_knowledgeRelation := knowledgeRelation{}

	_knowledgeRelation.knowledgeRelationDo.UseDB(db, opts...)
	_knowledgeRelation.knowledgeRelationDo.UseModel(&model.KnowledgeRelation{})

	tableName := _knowledgeRelation.knowledgeRelationDo.TableName()
	_knowledgeRelation.ALL = field.NewAsterisk(tableName)
	_knowledgeRelation.ID = field.NewInt64(tableName, "id")
	_knowledgeRelation.FromKnowledgeID = field.NewInt64(tableName, "from_knowledge_id")
	_knowledgeRelation.ToKnowledgeID = field.NewInt64(tableName, "to_knowledge_id")
	_knowledgeRelation.RelationType = field.NewString(tableName, "relation_type")

	_knowledgeRelation.fillFieldMap()

	return _knowledgeRelation
}

type knowledgeRelation struct {
	knowledgeRelationDo knowledgeRelationDo

	ALL             field.Asterisk
	ID              field.Int64
	FromKnowledgeID field.Int64
	ToKnowledgeID   field.Int64
	RelationType    field.String

	fieldMap map[string]field.Expr
}

func (k knowledgeRelation) Table(newTableName string) *knowledgeRelation {
	k.knowledgeRelationDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledgeRelation) As(alias string) *knowledgeRelation {
	k.knowledgeRelationDo.DO = *(k.knowledgeRelationDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledgeRelation) updateTableName(table string) *knowledgeRelation {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewInt64(table, "id")
	k.FromKnowledgeID = field.NewInt64(table, "from_knowledge_id")
	k.ToKnowledgeID = field.NewInt64(table, "to_knowledge_id")
	k.RelationType = field.NewString(table, "relation_type")

	k.fillFieldMap()

	return k
}

func (k *knowledgeRelation) WithContext(ctx context.Context) IKnowledgeRelationDo {
	return k.knowledgeRelationDo.WithContext(ctx)
}

func (k knowledgeRelation) TableName() string { return k.knowledgeRelationDo.TableName() }

func (k knowledgeRelation) Alias() string { return k.knowledgeRelationDo.Alias() }

func (k knowledgeRelation) Columns(cols ...field.Expr) gen.Columns {
	return k.knowledgeRelationDo.Columns(cols...)
}

func (k *knowledgeRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledgeRelation) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 4)
	k.fieldMap["id"] = k.ID
	k.fieldMap["from_knowledge_id"] = k.FromKnowledgeID
	k.fieldMap["to_knowledge_id"] = k.ToKnowledgeID
	k.fieldMap["relation_type"] = k.RelationType
}

func (k knowledgeRelation) clone(db *gorm.DB) knowledgeRelation {
	k.knowledgeRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k knowledgeRelation) replaceDB(db *gorm.DB) knowledgeRelation {
	k.knowledgeRelationDo.ReplaceDB(db)
	return k
}

type knowledgeRelationDo struct{ gen.DO }

type IKnowledgeRelationDo interface {
	gen.SubQuery
	Debug() IKnowledgeRelationDo
	WithContext(ctx context.Context) IKnowledgeRelationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKnowledgeRelationDo
	WriteDB() IKnowledgeRelationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKnowledgeRelationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKnowledgeRelationDo
	Not(conds ...gen.Condition) IKnowledgeRelationDo
	Or(conds ...gen.Condition) IKnowledgeRelationDo
	Select(conds ...field.Expr) IKnowledgeRelationDo
	Where(conds ...gen.Condition) IKnowledgeRelationDo
	Order(conds ...field.Expr) IKnowledgeRelationDo
	Distinct(cols ...field.Expr) IKnowledgeRelationDo
	Omit(cols ...field.Expr) IKnowledgeRelationDo
	Join(table schema.Tabler, on ...field.Expr) IKnowledgeRelationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeRelationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeRelationDo
	Group(cols ...field.Expr) IKnowledgeRelationDo
	Having(conds ...gen.Condition) IKnowledgeRelationDo
	Limit(limit int) IKnowledgeRelationDo
	Offset(offset int) IKnowledgeRelationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeRelationDo
	Unscoped() IKnowledgeRelationDo
	Create(values ...*model.KnowledgeRelation) error
	CreateInBatches(values []*model.KnowledgeRelation, batchSize int) error
	Save(values ...*model.KnowledgeRelation) error
	First() (*model.KnowledgeRelation, error)
	Take() (*model.KnowledgeRelation, error)
	Last() (*model.KnowledgeRelation, error)
	Find() ([]*model.KnowledgeRelation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KnowledgeRelation, err error)
	FindInBatches(result *[]*model.KnowledgeRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.KnowledgeRelation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKnowledgeRelationDo
	Assign(attrs ...field.AssignExpr) IKnowledgeRelationDo
	Joins(fields ...field.RelationField) IKnowledgeRelationDo
	Preload(fields ...field.RelationField) IKnowledgeRelationDo
	FirstOrInit() (*model.KnowledgeRelation, error)
	FirstOrCreate() (*model.KnowledgeRelation, error)
	FindByPage(offset int, limit int) (result []*model.KnowledgeRelation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKnowledgeRelationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k knowledgeRelationDo) Debug() IKnowledgeRelationDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgeRelationDo) WithContext(ctx context.Context) IKnowledgeRelationDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgeRelationDo) ReadDB() IKnowledgeRelationDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgeRelationDo) WriteDB() IKnowledgeRelationDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgeRelationDo) Session(config *gorm.Session) IKnowledgeRelationDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgeRelationDo) Clauses(conds ...clause.Expression) IKnowledgeRelationDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgeRelationDo) Returning(value interface{}, columns ...string) IKnowledgeRelationDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgeRelationDo) Not(conds ...gen.Condition) IKnowledgeRelationDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgeRelationDo) Or(conds ...gen.Condition) IKnowledgeRelationDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgeRelationDo) Select(conds ...field.Expr) IKnowledgeRelationDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgeRelationDo) Where(conds ...gen.Condition) IKnowledgeRelationDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgeRelationDo) Order(conds ...field.Expr) IKnowledgeRelationDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgeRelationDo) Distinct(cols ...field.Expr) IKnowledgeRelationDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgeRelationDo) Omit(cols ...field.Expr) IKnowledgeRelationDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgeRelationDo) Join(table schema.Tabler, on ...field.Expr) IKnowledgeRelationDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgeRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeRelationDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgeRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeRelationDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgeRelationDo) Group(cols ...field.Expr) IKnowledgeRelationDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgeRelationDo) Having(conds ...gen.Condition) IKnowledgeRelationDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgeRelationDo) Limit(limit int) IKnowledgeRelationDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgeRelationDo) Offset(offset int) IKnowledgeRelationDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgeRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeRelationDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgeRelationDo) Unscoped() IKnowledgeRelationDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgeRelationDo) Create(values ...*model.KnowledgeRelation) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgeRelationDo) CreateInBatches(values []*model.KnowledgeRelation, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgeRelationDo) Save(values ...*model.KnowledgeRelation) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgeRelationDo) First() (*model.KnowledgeRelation, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeRelation), nil
	}
}

func (k knowledgeRelationDo) Take() (*model.KnowledgeRelation, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeRelation), nil
	}
}

func (k knowledgeRelationDo) Last() (*model.KnowledgeRelation, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeRelation), nil
	}
}

func (k knowledgeRelationDo) Find() ([]*model.KnowledgeRelation, error) {
	result, err := k.DO.Find()
	return result.([]*model.KnowledgeRelation), err
}

func (k knowledgeRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KnowledgeRelation, err error) {
	buf := make([]*model.KnowledgeRelation, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgeRelationDo) FindInBatches(result *[]*model.KnowledgeRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgeRelationDo) Attrs(attrs ...field.AssignExpr) IKnowledgeRelationDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgeRelationDo) Assign(attrs ...field.AssignExpr) IKnowledgeRelationDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgeRelationDo) Joins(fields ...field.RelationField) IKnowledgeRelationDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgeRelationDo) Preload(fields ...field.RelationField) IKnowledgeRelationDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgeRelationDo) FirstOrInit() (*model.KnowledgeRelation, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeRelation), nil
	}
}

func (k knowledgeRelationDo) FirstOrCreate() (*model.KnowledgeRelation, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeRelation), nil
	}
}

func (k knowledgeRelationDo) FindByPage(offset int, limit int) (result []*model.KnowledgeRelation, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgeRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgeRelationDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgeRelationDo) Delete(models ...*model.KnowledgeRelation) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgeRelationDo) withDO(do gen.Dao) *knowledgeRelationDo {
	k.DO = *do.(*gen.DO)
	return k
}
