// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"techmemo/backend/model"
)

func newNoteVersion(db *gorm.DB, opts ...gen.DOOption) noteVersion {
	_noteVersion := noteVersion{}

	_noteVersion.noteVersionDo.UseDB(db, opts...)
	_noteVersion.noteVersionDo.UseModel(&model.NoteVersion{})

	tableName := _noteVersion.noteVersionDo.TableName()
	_noteVersion.ALL = field.NewAsterisk(tableName)
	_noteVersion.ID = field.NewInt64(tableName, "id")
	_noteVersion.NoteID = field.NewInt64(tableName, "note_id")
	_noteVersion.ContentMd = field.NewString(tableName, "content_md")
	_noteVersion.CreatedAt = field.NewTime(tableName, "created_at")

	_noteVersion.fillFieldMap()

	return _noteVersion
}

type noteVersion struct {
	noteVersionDo noteVersionDo

	ALL       field.Asterisk
	ID        field.Int64
	NoteID    field.Int64
	ContentMd field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (n noteVersion) Table(newTableName string) *noteVersion {
	n.noteVersionDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n noteVersion) As(alias string) *noteVersion {
	n.noteVersionDo.DO = *(n.noteVersionDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *noteVersion) updateTableName(table string) *noteVersion {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NoteID = field.NewInt64(table, "note_id")
	n.ContentMd = field.NewString(table, "content_md")
	n.CreatedAt = field.NewTime(table, "created_at")

	n.fillFieldMap()

	return n
}

func (n *noteVersion) WithContext(ctx context.Context) INoteVersionDo {
	return n.noteVersionDo.WithContext(ctx)
}

func (n noteVersion) TableName() string { return n.noteVersionDo.TableName() }

func (n noteVersion) Alias() string { return n.noteVersionDo.Alias() }

func (n noteVersion) Columns(cols ...field.Expr) gen.Columns { return n.noteVersionDo.Columns(cols...) }

func (n *noteVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *noteVersion) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 4)
	n.fieldMap["id"] = n.ID
	n.fieldMap["note_id"] = n.NoteID
	n.fieldMap["content_md"] = n.ContentMd
	n.fieldMap["created_at"] = n.CreatedAt
}

func (n noteVersion) clone(db *gorm.DB) noteVersion {
	n.noteVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n noteVersion) replaceDB(db *gorm.DB) noteVersion {
	n.noteVersionDo.ReplaceDB(db)
	return n
}

type noteVersionDo struct{ gen.DO }

type INoteVersionDo interface {
	gen.SubQuery
	Debug() INoteVersionDo
	WithContext(ctx context.Context) INoteVersionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INoteVersionDo
	WriteDB() INoteVersionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INoteVersionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INoteVersionDo
	Not(conds ...gen.Condition) INoteVersionDo
	Or(conds ...gen.Condition) INoteVersionDo
	Select(conds ...field.Expr) INoteVersionDo
	Where(conds ...gen.Condition) INoteVersionDo
	Order(conds ...field.Expr) INoteVersionDo
	Distinct(cols ...field.Expr) INoteVersionDo
	Omit(cols ...field.Expr) INoteVersionDo
	Join(table schema.Tabler, on ...field.Expr) INoteVersionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INoteVersionDo
	RightJoin(table schema.Tabler, on ...field.Expr) INoteVersionDo
	Group(cols ...field.Expr) INoteVersionDo
	Having(conds ...gen.Condition) INoteVersionDo
	Limit(limit int) INoteVersionDo
	Offset(offset int) INoteVersionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INoteVersionDo
	Unscoped() INoteVersionDo
	Create(values ...*model.NoteVersion) error
	CreateInBatches(values []*model.NoteVersion, batchSize int) error
	Save(values ...*model.NoteVersion) error
	First() (*model.NoteVersion, error)
	Take() (*model.NoteVersion, error)
	Last() (*model.NoteVersion, error)
	Find() ([]*model.NoteVersion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteVersion, err error)
	FindInBatches(result *[]*model.NoteVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NoteVersion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INoteVersionDo
	Assign(attrs ...field.AssignExpr) INoteVersionDo
	Joins(fields ...field.RelationField) INoteVersionDo
	Preload(fields ...field.RelationField) INoteVersionDo
	FirstOrInit() (*model.NoteVersion, error)
	FirstOrCreate() (*model.NoteVersion, error)
	FindByPage(offset int, limit int) (result []*model.NoteVersion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INoteVersionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n noteVersionDo) Debug() INoteVersionDo {
	return n.withDO(n.DO.Debug())
}

func (n noteVersionDo) WithContext(ctx context.Context) INoteVersionDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n noteVersionDo) ReadDB() INoteVersionDo {
	return n.Clauses(dbresolver.Read)
}

func (n noteVersionDo) WriteDB() INoteVersionDo {
	return n.Clauses(dbresolver.Write)
}

func (n noteVersionDo) Session(config *gorm.Session) INoteVersionDo {
	return n.withDO(n.DO.Session(config))
}

func (n noteVersionDo) Clauses(conds ...clause.Expression) INoteVersionDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n noteVersionDo) Returning(value interface{}, columns ...string) INoteVersionDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n noteVersionDo) Not(conds ...gen.Condition) INoteVersionDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n noteVersionDo) Or(conds ...gen.Condition) INoteVersionDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n noteVersionDo) Select(conds ...field.Expr) INoteVersionDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n noteVersionDo) Where(conds ...gen.Condition) INoteVersionDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n noteVersionDo) Order(conds ...field.Expr) INoteVersionDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n noteVersionDo) Distinct(cols ...field.Expr) INoteVersionDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n noteVersionDo) Omit(cols ...field.Expr) INoteVersionDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n noteVersionDo) Join(table schema.Tabler, on ...field.Expr) INoteVersionDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n noteVersionDo) LeftJoin(table schema.Tabler, on ...field.Expr) INoteVersionDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n noteVersionDo) RightJoin(table schema.Tabler, on ...field.Expr) INoteVersionDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n noteVersionDo) Group(cols ...field.Expr) INoteVersionDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n noteVersionDo) Having(conds ...gen.Condition) INoteVersionDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n noteVersionDo) Limit(limit int) INoteVersionDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n noteVersionDo) Offset(offset int) INoteVersionDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n noteVersionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INoteVersionDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n noteVersionDo) Unscoped() INoteVersionDo {
	return n.withDO(n.DO.Unscoped())
}

func (n noteVersionDo) Create(values ...*model.NoteVersion) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n noteVersionDo) CreateInBatches(values []*model.NoteVersion, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n noteVersionDo) Save(values ...*model.NoteVersion) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n noteVersionDo) First() (*model.NoteVersion, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteVersion), nil
	}
}

func (n noteVersionDo) Take() (*model.NoteVersion, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteVersion), nil
	}
}

func (n noteVersionDo) Last() (*model.NoteVersion, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteVersion), nil
	}
}

func (n noteVersionDo) Find() ([]*model.NoteVersion, error) {
	result, err := n.DO.Find()
	return result.([]*model.NoteVersion), err
}

func (n noteVersionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteVersion, err error) {
	buf := make([]*model.NoteVersion, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n noteVersionDo) FindInBatches(result *[]*model.NoteVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n noteVersionDo) Attrs(attrs ...field.AssignExpr) INoteVersionDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n noteVersionDo) Assign(attrs ...field.AssignExpr) INoteVersionDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n noteVersionDo) Joins(fields ...field.RelationField) INoteVersionDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n noteVersionDo) Preload(fields ...field.RelationField) INoteVersionDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n noteVersionDo) FirstOrInit() (*model.NoteVersion, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteVersion), nil
	}
}

func (n noteVersionDo) FirstOrCreate() (*model.NoteVersion, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteVersion), nil
	}
}

func (n noteVersionDo) FindByPage(offset int, limit int) (result []*model.NoteVersion, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n noteVersionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n noteVersionDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n noteVersionDo) Delete(models ...*model.NoteVersion) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *noteVersionDo) withDO(do gen.Dao) *noteVersionDo {
	n.DO = *do.(*gen.DO)
	return n
}
