// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"techmemo/backend/model"
)

func newNoteRootNode(db *gorm.DB, opts ...gen.DOOption) noteRootNode {
	_noteRootNode := noteRootNode{}

	_noteRootNode.noteRootNodeDo.UseDB(db, opts...)
	_noteRootNode.noteRootNodeDo.UseModel(&model.NoteRootNode{})

	tableName := _noteRootNode.noteRootNodeDo.TableName()
	_noteRootNode.ALL = field.NewAsterisk(tableName)
	_noteRootNode.ID = field.NewInt64(tableName, "id")
	_noteRootNode.NoteID = field.NewInt64(tableName, "note_id")
	_noteRootNode.RootKnowledgeID = field.NewInt64(tableName, "root_knowledge_id")
	_noteRootNode.Name = field.NewString(tableName, "name")
	_noteRootNode.Description = field.NewString(tableName, "description")
	_noteRootNode.ImportanceScore = field.NewFloat64(tableName, "importance_score")
	_noteRootNode.CreatedAt = field.NewTime(tableName, "created_at")

	_noteRootNode.fillFieldMap()

	return _noteRootNode
}

type noteRootNode struct {
	noteRootNodeDo noteRootNodeDo

	ALL             field.Asterisk
	ID              field.Int64
	NoteID          field.Int64
	RootKnowledgeID field.Int64
	Name            field.String
	Description     field.String
	ImportanceScore field.Float64
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (n noteRootNode) Table(newTableName string) *noteRootNode {
	n.noteRootNodeDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n noteRootNode) As(alias string) *noteRootNode {
	n.noteRootNodeDo.DO = *(n.noteRootNodeDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *noteRootNode) updateTableName(table string) *noteRootNode {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NoteID = field.NewInt64(table, "note_id")
	n.RootKnowledgeID = field.NewInt64(table, "root_knowledge_id")
	n.Name = field.NewString(table, "name")
	n.Description = field.NewString(table, "description")
	n.ImportanceScore = field.NewFloat64(table, "importance_score")
	n.CreatedAt = field.NewTime(table, "created_at")

	n.fillFieldMap()

	return n
}

func (n *noteRootNode) WithContext(ctx context.Context) INoteRootNodeDo {
	return n.noteRootNodeDo.WithContext(ctx)
}

func (n noteRootNode) TableName() string { return n.noteRootNodeDo.TableName() }

func (n noteRootNode) Alias() string { return n.noteRootNodeDo.Alias() }

func (n noteRootNode) Columns(cols ...field.Expr) gen.Columns {
	return n.noteRootNodeDo.Columns(cols...)
}

func (n *noteRootNode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *noteRootNode) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 7)
	n.fieldMap["id"] = n.ID
	n.fieldMap["note_id"] = n.NoteID
	n.fieldMap["root_knowledge_id"] = n.RootKnowledgeID
	n.fieldMap["name"] = n.Name
	n.fieldMap["description"] = n.Description
	n.fieldMap["importance_score"] = n.ImportanceScore
	n.fieldMap["created_at"] = n.CreatedAt
}

func (n noteRootNode) clone(db *gorm.DB) noteRootNode {
	n.noteRootNodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n noteRootNode) replaceDB(db *gorm.DB) noteRootNode {
	n.noteRootNodeDo.ReplaceDB(db)
	return n
}

type noteRootNodeDo struct{ gen.DO }

type INoteRootNodeDo interface {
	gen.SubQuery
	Debug() INoteRootNodeDo
	WithContext(ctx context.Context) INoteRootNodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INoteRootNodeDo
	WriteDB() INoteRootNodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INoteRootNodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INoteRootNodeDo
	Not(conds ...gen.Condition) INoteRootNodeDo
	Or(conds ...gen.Condition) INoteRootNodeDo
	Select(conds ...field.Expr) INoteRootNodeDo
	Where(conds ...gen.Condition) INoteRootNodeDo
	Order(conds ...field.Expr) INoteRootNodeDo
	Distinct(cols ...field.Expr) INoteRootNodeDo
	Omit(cols ...field.Expr) INoteRootNodeDo
	Join(table schema.Tabler, on ...field.Expr) INoteRootNodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INoteRootNodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) INoteRootNodeDo
	Group(cols ...field.Expr) INoteRootNodeDo
	Having(conds ...gen.Condition) INoteRootNodeDo
	Limit(limit int) INoteRootNodeDo
	Offset(offset int) INoteRootNodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INoteRootNodeDo
	Unscoped() INoteRootNodeDo
	Create(values ...*model.NoteRootNode) error
	CreateInBatches(values []*model.NoteRootNode, batchSize int) error
	Save(values ...*model.NoteRootNode) error
	First() (*model.NoteRootNode, error)
	Take() (*model.NoteRootNode, error)
	Last() (*model.NoteRootNode, error)
	Find() ([]*model.NoteRootNode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteRootNode, err error)
	FindInBatches(result *[]*model.NoteRootNode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NoteRootNode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INoteRootNodeDo
	Assign(attrs ...field.AssignExpr) INoteRootNodeDo
	Joins(fields ...field.RelationField) INoteRootNodeDo
	Preload(fields ...field.RelationField) INoteRootNodeDo
	FirstOrInit() (*model.NoteRootNode, error)
	FirstOrCreate() (*model.NoteRootNode, error)
	FindByPage(offset int, limit int) (result []*model.NoteRootNode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INoteRootNodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n noteRootNodeDo) Debug() INoteRootNodeDo {
	return n.withDO(n.DO.Debug())
}

func (n noteRootNodeDo) WithContext(ctx context.Context) INoteRootNodeDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n noteRootNodeDo) ReadDB() INoteRootNodeDo {
	return n.Clauses(dbresolver.Read)
}

func (n noteRootNodeDo) WriteDB() INoteRootNodeDo {
	return n.Clauses(dbresolver.Write)
}

func (n noteRootNodeDo) Session(config *gorm.Session) INoteRootNodeDo {
	return n.withDO(n.DO.Session(config))
}

func (n noteRootNodeDo) Clauses(conds ...clause.Expression) INoteRootNodeDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n noteRootNodeDo) Returning(value interface{}, columns ...string) INoteRootNodeDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n noteRootNodeDo) Not(conds ...gen.Condition) INoteRootNodeDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n noteRootNodeDo) Or(conds ...gen.Condition) INoteRootNodeDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n noteRootNodeDo) Select(conds ...field.Expr) INoteRootNodeDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n noteRootNodeDo) Where(conds ...gen.Condition) INoteRootNodeDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n noteRootNodeDo) Order(conds ...field.Expr) INoteRootNodeDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n noteRootNodeDo) Distinct(cols ...field.Expr) INoteRootNodeDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n noteRootNodeDo) Omit(cols ...field.Expr) INoteRootNodeDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n noteRootNodeDo) Join(table schema.Tabler, on ...field.Expr) INoteRootNodeDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n noteRootNodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) INoteRootNodeDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n noteRootNodeDo) RightJoin(table schema.Tabler, on ...field.Expr) INoteRootNodeDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n noteRootNodeDo) Group(cols ...field.Expr) INoteRootNodeDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n noteRootNodeDo) Having(conds ...gen.Condition) INoteRootNodeDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n noteRootNodeDo) Limit(limit int) INoteRootNodeDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n noteRootNodeDo) Offset(offset int) INoteRootNodeDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n noteRootNodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INoteRootNodeDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n noteRootNodeDo) Unscoped() INoteRootNodeDo {
	return n.withDO(n.DO.Unscoped())
}

func (n noteRootNodeDo) Create(values ...*model.NoteRootNode) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n noteRootNodeDo) CreateInBatches(values []*model.NoteRootNode, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n noteRootNodeDo) Save(values ...*model.NoteRootNode) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n noteRootNodeDo) First() (*model.NoteRootNode, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRootNode), nil
	}
}

func (n noteRootNodeDo) Take() (*model.NoteRootNode, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRootNode), nil
	}
}

func (n noteRootNodeDo) Last() (*model.NoteRootNode, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRootNode), nil
	}
}

func (n noteRootNodeDo) Find() ([]*model.NoteRootNode, error) {
	result, err := n.DO.Find()
	return result.([]*model.NoteRootNode), err
}

func (n noteRootNodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NoteRootNode, err error) {
	buf := make([]*model.NoteRootNode, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n noteRootNodeDo) FindInBatches(result *[]*model.NoteRootNode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n noteRootNodeDo) Attrs(attrs ...field.AssignExpr) INoteRootNodeDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n noteRootNodeDo) Assign(attrs ...field.AssignExpr) INoteRootNodeDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n noteRootNodeDo) Joins(fields ...field.RelationField) INoteRootNodeDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n noteRootNodeDo) Preload(fields ...field.RelationField) INoteRootNodeDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n noteRootNodeDo) FirstOrInit() (*model.NoteRootNode, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRootNode), nil
	}
}

func (n noteRootNodeDo) FirstOrCreate() (*model.NoteRootNode, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NoteRootNode), nil
	}
}

func (n noteRootNodeDo) FindByPage(offset int, limit int) (result []*model.NoteRootNode, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n noteRootNodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n noteRootNodeDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n noteRootNodeDo) Delete(models ...*model.NoteRootNode) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *noteRootNodeDo) withDO(do gen.Dao) *noteRootNodeDo {
	n.DO = *do.(*gen.DO)
	return n
}
