// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAiProcessLog = "ai_process_log"

// AiProcessLog mapped from table <ai_process_log>
type AiProcessLog struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TargetType  string    `gorm:"column:target_type;not null" json:"target_type"`
	TargetID    int64     `gorm:"column:target_id;not null" json:"target_id"`
	ProcessType string    `gorm:"column:process_type;not null" json:"process_type"`
	ModelName   string    `gorm:"column:model_name;not null" json:"model_name"`
	Status      string    `gorm:"column:status;default:success" json:"status"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName AiProcessLog's table name
func (*AiProcessLog) TableName() string {
	return TableNameAiProcessLog
}
