// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatMessage = "chat_message"

// ChatMessage mapped from table <chat_message>
type ChatMessage struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SessionID  int64     `gorm:"column:session_id;not null" json:"session_id"`
	UserID     int64     `gorm:"column:user_id;not null" json:"user_id"`
	Role       string    `gorm:"column:role;not null" json:"role"`
	Content    string    `gorm:"column:content;not null" json:"content"`
	TokenCount int32     `gorm:"column:token_count" json:"token_count"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName ChatMessage's table name
func (*ChatMessage) TableName() string {
	return TableNameChatMessage
}
