// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmbedding = "embedding"

// Embedding mapped from table <embedding>
type Embedding struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TargetType string    `gorm:"column:target_type;not null" json:"target_type"`
	TargetID   int64     `gorm:"column:target_id;not null" json:"target_id"`
	Vector     string    `gorm:"column:vector" json:"vector"`
	ModelName  string    `gorm:"column:model_name;not null" json:"model_name"`
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName Embedding's table name
func (*Embedding) TableName() string {
	return TableNameEmbedding
}
