// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKnowledgeRelation = "knowledge_relation"

// KnowledgeRelation mapped from table <knowledge_relation>
type KnowledgeRelation struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FromKnowledgeID int64  `gorm:"column:from_knowledge_id;not null" json:"from_knowledge_id"`
	ToKnowledgeID   int64  `gorm:"column:to_knowledge_id;not null" json:"to_knowledge_id"`
	RelationType    string `gorm:"column:relation_type" json:"relation_type"`
}

// TableName KnowledgeRelation's table name
func (*KnowledgeRelation) TableName() string {
	return TableNameKnowledgeRelation
}
