// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKnowledgePoint = "knowledge_point"

// KnowledgePoint mapped from table <knowledge_point>
type KnowledgePoint struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID          int64     `gorm:"column:user_id;not null" json:"user_id"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	Description     string    `gorm:"column:description" json:"description"`
	SourceNoteID    int64     `gorm:"column:source_note_id" json:"source_note_id"`
	ImportanceScore float64   `gorm:"column:importance_score" json:"importance_score"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName KnowledgePoint's table name
func (*KnowledgePoint) TableName() string {
	return TableNameKnowledgePoint
}
