// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNoteTag = "note_tag"

// NoteTag mapped from table <note_tag>
type NoteTag struct {
	NoteID int64 `gorm:"column:note_id;primaryKey" json:"note_id"`
	TagID  int64 `gorm:"column:tag_id;primaryKey" json:"tag_id"`
}

// TableName NoteTag's table name
func (*NoteTag) TableName() string {
	return TableNameNoteTag
}
