// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNote = "note"

// Note mapped from table <note>
type Note struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;not null" json:"user_id"`
	Title      string    `gorm:"column:title;not null" json:"title"`
	ContentMd  string    `gorm:"column:content_md;not null" json:"content_md"`
	NoteType   string    `gorm:"column:note_type;default:unknown" json:"note_type"`
	CategoryID int64     `gorm:"column:category_id" json:"category_id"`
	Status     string    `gorm:"column:status;default:normal" json:"status"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Note's table name
func (*Note) TableName() string {
	return TableNameNote
}
