// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNoteRootNode = "note_root_node"

// NoteRootNode mapped from table <note_root_node>
type NoteRootNode struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NoteID          int64     `gorm:"column:note_id;not null" json:"note_id"`
	RootKnowledgeID int64     `gorm:"column:root_knowledge_id;not null" json:"root_knowledge_id"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	Description     string    `gorm:"column:description" json:"description"`
	ImportanceScore float64   `gorm:"column:importance_score" json:"importance_score"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName NoteRootNode's table name
func (*NoteRootNode) TableName() string {
	return TableNameNoteRootNode
}
