// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSearchHistory = "search_history"

// SearchHistory mapped from table <search_history>
type SearchHistory struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
	Keyword        string    `gorm:"column:keyword;not null" json:"keyword"`
	SearchType     string    `gorm:"column:search_type;default:keyword" json:"search_type"`
	LastSearchedAt time.Time `gorm:"column:last_searched_at;not null" json:"last_searched_at"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	TargetType     string    `gorm:"column:target_type;not null" json:"target_type"`
}

// TableName SearchHistory's table name
func (*SearchHistory) TableName() string {
	return TableNameSearchHistory
}
