// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username     string    `gorm:"column:username;not null" json:"username"`
	PasswordHash string    `gorm:"column:password_hash;not null" json:"password_hash"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
